

GET http://localhost:3000/pokemon


###

GET http://localhost:3000/pokemon/66150701143cfa55d369fb56

### 

POST http://localhost:3000/pokemon
Content-Type: application/json

{
    "Name": "Deoxys",
    "Type": "Psy"
}

### 

PUT http://localhost:3000/pokemon/6615073a143cfa55d369fb5a
Content-Type: application/json

{
    "Name": "Regigigas",
    "Type": "Normal"
}

###

DELETE http://localhost:3000/pokemon/6615073a143cfa55d369fb5a